import type { FinanceData } from "./types";

export const CASHFLOW_SEED: FinanceData = {
  accounts: [
    {
      id: "acc-salary",
      name: "A · Salary Clearing",
      bankName: "Up Bank",
      type: "Salary",
      balance: 2450,
      openingBalance: 2450,
      currency: "AUD",
      color: "#6f74e8",
      icon: "A",
      notes: "Income lands here before allocation.",
      archived: false,
      rule: "Income only · no card spending",
      purpose: "salary",
    },
    {
      id: "acc-everyday",
      name: "B · Everyday",
      bankName: "Commonwealth",
      type: "Transaction",
      balance: 1284.37,
      openingBalance: 1284.37,
      currency: "AUD",
      color: "#ec7c69",
      icon: "B",
      notes: "Daily card purchases and transport.",
      archived: false,
      rule: "Daily spending only",
      purpose: "daily",
    },
    {
      id: "acc-bills",
      name: "B+ · Bills Reserve",
      bankName: "ING",
      type: "Bills",
      balance: 3420,
      openingBalance: 3420,
      currency: "AUD",
      color: "#e2a84b",
      icon: "B+",
      notes: "Ring-fenced rent, utilities and loan payments.",
      archived: false,
      rule: "Essential scheduled bills",
      purpose: "bills",
    },
    {
      id: "acc-global",
      name: "C · Global & Subs",
      bankName: "Wise",
      type: "International",
      balance: 620.88,
      openingBalance: 620.88,
      currency: "AUD",
      color: "#28a989",
      icon: "C",
      notes: "Online subscriptions and international payments.",
      archived: false,
      rule: "Subscriptions and international",
      purpose: "international",
    },
    {
      id: "acc-future",
      name: "D · Future Fund",
      bankName: "Macquarie",
      type: "Savings",
      balance: 28750,
      openingBalance: 28750,
      currency: "AUD",
      color: "#4f8fd8",
      icon: "D",
      notes: "Emergency fund and long-term savings.",
      archived: false,
      rule: "Long-term savings · withdrawals reviewed",
      purpose: "savings",
    },
  ],
  categories: [
    { id: "cat-salary", name: "Salary", kind: "income", color: "#28a989", icon: "↗" },
    { id: "cat-freelance", name: "Freelance", kind: "income", color: "#4f8fd8", icon: "↗" },
    { id: "cat-rent", name: "Rent", kind: "expense", color: "#6f74e8", icon: "⌂" },
    { id: "cat-groceries", name: "Groceries", kind: "expense", color: "#28a989", icon: "G" },
    { id: "cat-transport", name: "Transport", kind: "expense", color: "#e2a84b", icon: "T" },
    { id: "cat-dining", name: "Dining", kind: "expense", color: "#ec7c69", icon: "D" },
    { id: "cat-utilities", name: "Utilities", kind: "expense", color: "#4f8fd8", icon: "U" },
    { id: "cat-subscriptions", name: "Subscriptions", kind: "expense", color: "#9b72cf", icon: "S" },
    { id: "cat-entertainment", name: "Entertainment", kind: "expense", color: "#e76881", icon: "E" },
    { id: "cat-savings", name: "Savings", kind: "both", color: "#3997a8", icon: "◎" },
    { id: "cat-other", name: "Other", kind: "both", color: "#8f98a7", icon: "·" },
  ],
  transactions: [
    {
      id: "txn-1",
      title: "Salary · Northstar Studio",
      description: "Fortnightly salary",
      amount: 6850,
      type: "income",
      categoryId: "cat-salary",
      accountId: "acc-salary",
      date: "2026-07-15",
      time: "09:00",
      merchant: "Northstar Studio",
      paymentMethod: "Bank transfer",
      tags: ["salary"],
      notes: "",
      location: "Melbourne VIC",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-2",
      title: "Brand strategy project",
      description: "Final freelance invoice",
      amount: 1145,
      type: "income",
      categoryId: "cat-freelance",
      accountId: "acc-salary",
      date: "2026-07-08",
      time: "14:35",
      merchant: "Juniper & Co",
      paymentMethod: "Bank transfer",
      tags: ["freelance"],
      notes: "Invoice JN-104",
      location: "Melbourne VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-3",
      title: "Monthly rent",
      description: "July apartment rent",
      amount: 2480,
      type: "expense",
      categoryId: "cat-rent",
      accountId: "acc-bills",
      date: "2026-07-01",
      time: "08:00",
      merchant: "Little Collins Property",
      paymentMethod: "Direct debit",
      tags: ["essential", "home"],
      notes: "",
      location: "Melbourne VIC",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-4",
      title: "Woolworths",
      description: "Weekly groceries",
      amount: 186.42,
      type: "expense",
      categoryId: "cat-groceries",
      accountId: "acc-everyday",
      date: "2026-07-24",
      time: "18:20",
      merchant: "Woolworths QV",
      paymentMethod: "Apple Pay",
      tags: ["weekly"],
      notes: "",
      location: "Melbourne VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-5",
      title: "Queen Victoria Market",
      description: "Fresh produce and pantry",
      amount: 251.58,
      type: "expense",
      categoryId: "cat-groceries",
      accountId: "acc-everyday",
      date: "2026-07-18",
      time: "11:10",
      merchant: "Queen Victoria Market",
      paymentMethod: "Debit card",
      tags: ["groceries"],
      notes: "",
      location: "Melbourne VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-6",
      title: "Metro fuel",
      description: "Fuel",
      amount: 91.76,
      type: "expense",
      categoryId: "cat-transport",
      accountId: "acc-bills",
      date: "2026-07-20",
      time: "07:42",
      merchant: "Metro Petroleum",
      paymentMethod: "Debit card",
      tags: ["car"],
      notes: "",
      location: "Richmond VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-7",
      title: "myki auto top-up",
      description: "Public transport",
      amount: 200.24,
      type: "expense",
      categoryId: "cat-transport",
      accountId: "acc-bills",
      date: "2026-07-11",
      time: "07:30",
      merchant: "Public Transport Victoria",
      paymentMethod: "Direct debit",
      tags: ["commute"],
      notes: "",
      location: "Melbourne VIC",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-8",
      title: "Origin Energy",
      description: "Electricity",
      amount: 164.3,
      type: "expense",
      categoryId: "cat-utilities",
      accountId: "acc-bills",
      date: "2026-07-17",
      time: "06:00",
      merchant: "Origin Energy",
      paymentMethod: "Direct debit",
      tags: ["home"],
      notes: "",
      location: "",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-9",
      title: "Netflix",
      description: "Standard plan",
      amount: 25.99,
      type: "expense",
      categoryId: "cat-subscriptions",
      accountId: "acc-global",
      date: "2026-07-22",
      time: "01:05",
      merchant: "Netflix",
      paymentMethod: "Visa",
      tags: ["subscription"],
      notes: "",
      location: "",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-10",
      title: "Apple iCloud+",
      description: "2TB storage",
      amount: 14.99,
      type: "expense",
      categoryId: "cat-subscriptions",
      accountId: "acc-global",
      date: "2026-07-21",
      time: "02:10",
      merchant: "Apple",
      paymentMethod: "Mastercard",
      tags: ["subscription"],
      notes: "",
      location: "",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-11",
      title: "Adobe Creative Cloud",
      description: "Creative suite",
      amount: 85.02,
      type: "expense",
      categoryId: "cat-subscriptions",
      accountId: "acc-global",
      date: "2026-07-12",
      time: "02:05",
      merchant: "Adobe",
      paymentMethod: "Mastercard",
      tags: ["work", "subscription"],
      notes: "",
      location: "",
      recurring: true,
      status: "completed",
    },
    {
      id: "txn-12",
      title: "Lune Coffee",
      description: "Coffee with Sam",
      amount: 7.8,
      type: "expense",
      categoryId: "cat-dining",
      accountId: "acc-everyday",
      date: "2026-07-25",
      time: "10:18",
      merchant: "Lune Croissanterie",
      paymentMethod: "Apple Pay",
      tags: ["coffee"],
      notes: "",
      location: "Fitzroy VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-13",
      title: "Dining & takeaway",
      description: "July dining",
      amount: 206.2,
      type: "expense",
      categoryId: "cat-dining",
      accountId: "acc-everyday",
      date: "2026-07-19",
      time: "19:30",
      merchant: "Various",
      paymentMethod: "Apple Pay",
      tags: ["food"],
      notes: "",
      location: "Melbourne VIC",
      recurring: false,
      status: "completed",
    },
    {
      id: "txn-14",
      title: "Arts Centre & cinema",
      description: "July entertainment",
      amount: 248,
      type: "expense",
      categoryId: "cat-entertainment",
      accountId: "acc-everyday",
      date: "2026-07-13",
      time: "20:00",
      merchant: "Various",
      paymentMethod: "Debit card",
      tags: ["fun"],
      notes: "",
      location: "Melbourne VIC",
      recurring: false,
      status: "completed",
    },
  ],
  transfers: [
    {
      id: "trf-1",
      fromAccountId: "acc-salary",
      toAccountId: "acc-future",
      amount: 1200,
      date: "2026-07-16",
      notes: "Automatic Future Fund contribution",
      status: "completed",
    },
    {
      id: "trf-2",
      fromAccountId: "acc-salary",
      toAccountId: "acc-bills",
      amount: 3200,
      date: "2026-07-16",
      notes: "Monthly bills allocation",
      status: "completed",
    },
  ],
  budgets: [
    { id: "bud-1", name: "Groceries", categoryId: "cat-groceries", monthlyLimit: 650, weeklyLimit: 150, dailyLimit: 24, periodStart: "2026-07-01", status: "active" },
    { id: "bud-2", name: "Transport", categoryId: "cat-transport", monthlyLimit: 360, weeklyLimit: 85, dailyLimit: 14, periodStart: "2026-07-01", status: "active" },
    { id: "bud-3", name: "Dining", categoryId: "cat-dining", monthlyLimit: 300, weeklyLimit: 75, dailyLimit: 11, periodStart: "2026-07-01", status: "active" },
    { id: "bud-4", name: "Subscriptions", categoryId: "cat-subscriptions", monthlyLimit: 150, weeklyLimit: 35, dailyLimit: 5, periodStart: "2026-07-01", status: "active" },
    { id: "bud-5", name: "Entertainment", categoryId: "cat-entertainment", monthlyLimit: 220, weeklyLimit: 55, dailyLimit: 8, periodStart: "2026-07-01", status: "active" },
  ],
  goals: [
    { id: "goal-1", name: "Emergency fund", targetAmount: 30000, currentAmount: 28750, deadline: "2026-10-31", monthlyContribution: 625, notes: "Six months of essential expenses.", color: "#28a989" },
    { id: "goal-2", name: "Japan trip", targetAmount: 8500, currentAmount: 4960, deadline: "2027-03-01", monthlyContribution: 450, notes: "Flights, rail pass and accommodation.", color: "#6f74e8" },
    { id: "goal-3", name: "Home deposit", targetAmount: 100000, currentAmount: 42300, deadline: "2029-06-30", monthlyContribution: 1400, notes: "First-home deposit target.", color: "#4f8fd8" },
  ],
  bills: [
    { id: "bill-1", name: "Internet", amount: 89, dueDate: "2026-07-29", accountId: "acc-bills", categoryId: "cat-utilities", reminderDays: 3, frequency: "monthly", status: "upcoming", autopay: true },
    { id: "bill-2", name: "Mobile phone", amount: 59, dueDate: "2026-07-31", accountId: "acc-bills", categoryId: "cat-utilities", reminderDays: 3, frequency: "monthly", status: "upcoming", autopay: true },
    { id: "bill-3", name: "Monthly rent", amount: 2480, dueDate: "2026-08-01", accountId: "acc-bills", categoryId: "cat-rent", reminderDays: 5, frequency: "monthly", status: "upcoming", autopay: true },
    { id: "bill-4", name: "Car loan", amount: 420, dueDate: "2026-08-03", accountId: "acc-bills", categoryId: "cat-transport", reminderDays: 4, frequency: "monthly", status: "upcoming", autopay: false },
    { id: "bill-5", name: "Home insurance", amount: 132.4, dueDate: "2026-07-19", accountId: "acc-bills", categoryId: "cat-utilities", reminderDays: 5, frequency: "monthly", status: "overdue", autopay: false },
  ],
  activity: [],
};
